name: cmtpr example
on: pull_request
jobs:
  example:
    name: example
    runs-on: ubuntu-latest
    steps:
      - name: comment PR
        uses: khezen/cmtpr@master
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        with:
          msg: "Looks good to me!"
